// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBmPvkVBIJ9VcPKIwYZj-YkfISvvi42ptk',
    appId: '1:445518370487:web:e6f4e5c93e27baaf015f32',
    messagingSenderId: '445518370487',
    projectId: 'wingapro-c343e',
    authDomain: 'wingapro-c343e.firebaseapp.com',
    storageBucket: 'wingapro-c343e.firebasestorage.app',
    measurementId: 'G-DNGHJTNGZ6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAoBlvr-LPbluHb31R-20SH7q1hHIXRkh4',
    appId: '1:445518370487:android:9d41f1fe1c2044db015f32',
    messagingSenderId: '445518370487',
    projectId: 'wingapro-c343e',
    storageBucket: 'wingapro-c343e.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA_ijUTo20wSBLuhYn1KEipKFMN1tKBAsI',
    appId: '1:445518370487:ios:70b10a9c2aa0bd5b015f32',
    messagingSenderId: '445518370487',
    projectId: 'wingapro-c343e',
    storageBucket: 'wingapro-c343e.firebasestorage.app',
    iosBundleId: 'com.example.wingapro2frontend',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA_ijUTo20wSBLuhYn1KEipKFMN1tKBAsI',
    appId: '1:445518370487:ios:70b10a9c2aa0bd5b015f32',
    messagingSenderId: '445518370487',
    projectId: 'wingapro-c343e',
    storageBucket: 'wingapro-c343e.firebasestorage.app',
    iosBundleId: 'com.example.wingapro2frontend',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBmPvkVBIJ9VcPKIwYZj-YkfISvvi42ptk',
    appId: '1:445518370487:web:855fab35e19f06f8015f32',
    messagingSenderId: '445518370487',
    projectId: 'wingapro-c343e',
    authDomain: 'wingapro-c343e.firebaseapp.com',
    storageBucket: 'wingapro-c343e.firebasestorage.app',
    measurementId: 'G-HJB8JMSK75',
  );
}
